name: Deploy Static Website to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Upload files to Azure Storage
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
              --account-key ${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }} \
              --source . \
              --destination '$web' \
              --overwrite

